management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: aftersale
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  config:
    import: classpath:strategy-rules.yml

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      database: 0
      password: 123456
      repositories:
        enabled: false
  datasource:
    #JDBC drivers
    driver-class-name: com.mysql.cj.jdbc.Driver
    #database url
    url: jdbc:mysql://localhost:3306/aftersale?serverTimezone=Asia/Shanghai&useSSL=false
    #    url: jdbc:mysql://mysql:3306Asia/Shanghai
    #database username and password
    username: "root"
    password: "123456"
server:
  port: 8080

service-module:
  url: http://localhost:8085

prodorder-module:
  url: prodorder:8080

payment-module:
  url: payment:8080

logistics-module:
  url: logistics:8080

oomall:
  core:
    page-size:
      max: 1000
      default: 10
  region:
    timeout: 3600