spring:
  application:
    name: aftersale
  cloud:
      compatibility-verifier:
       enabled: false
  datasource:
    #JDBC drivers
    driver-class-name: com.mysql.cj.jdbc.Driver
    #database url
    url: jdbc:mysql://localhost:3306/aftersale?serverTimezone=Asia/Shanghai&useSSL=false
    #    url: jdbc:mysql://mysql:3306Asia/Shanghai
    #database username and password
    username: "root"
    password: "@Song123"
server:
  port: 8080

